on:
  issues:
    types: [opened]

jobs:
  issue_labeler:
    if: github.repository == 'Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8'
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: Legends-of-Azeroth/GitHub-Actions@issue-labeler-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
