on:
  pull_request_target:
    types: [opened]

jobs:
  pr_labeler:
    runs-on: ubuntu-latest
    name: Pull Request Labeler
    steps:
    - name: Pull Request Labeler
      id: pr-labeler
      uses: Legends-of-Azeroth/GitHub-Actions@pr-labeler-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
