DELETE FROM `battleground_template` WHERE `id`=699;
INSERT INTO `battleground_template` (`id`, `MinPlayersPerTeam`, `MaxPlayersPerTeam`, `MinLvl`, `MaxLvl`, `AllianceStartLoc`, `AllianceStartO`, `HordeStartLoc`, `HordeStartO`, `StartMaxDist`, `Weight`, `ScriptName`, `Comment`) VALUES (699, 5, 10, 90, 100, 4059, 1.59375, 4060, 4.70393, 30, 3, '', 'Temple of Kotmogu');
DELETE FROM `battleground_template` WHERE `id`=708;
INSERT INTO `battleground_template` (`id`, `MinPlayersPerTeam`, `MaxPlayersPerTeam`, `MinLvl`, `MaxLvl`, `AllianceStartLoc`, `AllianceStartO`, `HordeStartLoc`, `HordeStartO`, `StartMaxDist`, `Weight`, `ScriptName`, `Comment`) VALUES (708, 5, 10, 90, 100, 4062, 5.59277, 4061, 5.57851, 50, 3, '', 'Silvershard Mines');
DELETE FROM `battleground_template` WHERE `id`=719;
INSERT INTO `battleground_template` (`id`, `MinPlayersPerTeam`, `MaxPlayersPerTeam`, `MinLvl`, `MaxLvl`, `AllianceStartLoc`, `AllianceStartO`, `HordeStartLoc`, `HordeStartO`, `StartMaxDist`, `Weight`, `ScriptName`, `Comment`) VALUES (719, 0, 5, 90, 100, 4136, 0, 4137, 0, 0, 1, '', 'Tol\'viron Arena');
DELETE FROM `battleground_template` WHERE `id`=754;
INSERT INTO `battleground_template` (`id`, `MinPlayersPerTeam`, `MaxPlayersPerTeam`, `MinLvl`, `MaxLvl`, `AllianceStartLoc`, `AllianceStartO`, `HordeStartLoc`, `HordeStartO`, `StartMaxDist`, `Weight`, `ScriptName`, `Comment`) VALUES (754, 5, 15, 90, 100, 4487, 0.659077, 4486, 4.04895, 100, 2, '', 'Deepwind Gorge');
DELETE FROM `battleground_template` WHERE `id`=757;
INSERT INTO `battleground_template` (`id`, `MinPlayersPerTeam`, `MaxPlayersPerTeam`, `MinLvl`, `MaxLvl`, `AllianceStartLoc`, `AllianceStartO`, `HordeStartLoc`, `HordeStartO`, `StartMaxDist`, `Weight`, `ScriptName`, `Comment`) VALUES (757, 0, 5, 90, 100, 4534, 0, 4535, 0, 0, 1, '', 'The Tiger\'s Peak');
